# ================================================================
# Book settings
# ================================================================
title: Proximité urbaine
author: Hazim Moindze (CINaM/CNRS/AMU)
logo: images/carte.png
language: fr

# ================================================================
# Execution (myst-nb)
# ================================================================
execute:
  # "auto" = n’exécute que si sorties manquantes/obsolètes
  # "force" = réexécute toujours tout
  execute_notebooks: "off"
  timeout: 600            # ↑ si certaines cellules sont longues
  allow_errors: false     # stoppe le build si erreur
  cache: _build/.jupyter_cache

# ================================================================
# PDF/LaTeX
# ================================================================
latex:
  latex_documents:
    targetname: AttractiveCity.tex

# ================================================================
# Références (BibTeX)
# ================================================================
bibtex_bibfiles:
  - references.bib

# ================================================================
# Liens dépôt
# ================================================================
repository:
  url: https://github.com/techByHazim/UrbanBook
  path_to_book: .
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: true
  favicon: images/carte.png
  analytics:
    google_analytics_id: ""   # J'ai pas encore de GA
  extra_footer: |
    <div style="font-size:0.9rem; line-height:1.4; margin-top:0.5rem;">
      Contact : <a href="mailto:hazim@cinam.univ-mrs.fr">moindze-boina.hazim@cnrs.fr</a>
    </div>

# ================================================================
# Lancement interactif
# ================================================================

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""   # à activer plus tard si j'allèges l'env
  colab_url: ""       # à activer seulement pour des .ipynb ciblés
  thebe: false        # Je garde off (env lourd)
