name: geo_env
channels:
  - conda-forge
channel_priority: strict

dependencies:
  # --- Python & base ---
  - python=3.10
  - pip

  # --- NumPy / Data ---
  - numpy
  - pandas
  - pyarrow

  # --- Geo stack (conda-forge résout les ABI) ---
  - geopandas
  - shapely
  - fiona
  - pyproj
  - rtree
  - gdal
  - rasterio
  - contextily
  - osmnx
  - pyosmium
  - osmium-tool

  # --- Science / ML / Viz ---
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - plotly

  # --- Graphes / utils ---
  - networkx
  - requests
  - tqdm

  # --- Jupyter & doc ---
  - jupyterlab
  - ipykernel
  - jupyter-book
  - myst-nb
  - streamlit
  
